// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppGoodsAction: typeof import('./src/components/search/AppGoodsAction.vue')['default']
    Apptabbar: typeof import('./src/components/search/Apptabbar.vue')['default']
    Dingdan: typeof import('./src/components/cart/Dingdan.vue')['default']
    Grid: typeof import('./src/components/home/Grid.vue')['default']
    HistoryHot: typeof import('./src/components/search/HistoryHot.vue')['default']
    Item: typeof import('./src/components/home/Item.vue')['default']
    Products: typeof import('./src/components/search/Products.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchProductList: typeof import('./src/components/search/searchProductList.vue')['default']
    SearchTipsList: typeof import('./src/components/search/SearchTipsList.vue')['default']
    Topic: typeof import('./src/components/home/Topic.vue')['default']
    Zhizao: typeof import('./src/components/home/Zhizao.vue')['default']
  }
}
